# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hello_world_hw/hello_world_hw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_world_hw || ORIG_REF_NAME==hello_world_hw} -quiet] -quiet

# IP: bd/hello_world_hw/ip/hello_world_hw_zynq_ultra_ps_e_0_0/hello_world_hw_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hello_world_hw_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==hello_world_hw_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: bd/hello_world_hw/hello_world_hw_ooc.xdc
